name: ADF-CICD-Pipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main 


pool:
  vmImage: "ubuntu-latest"

stages:
- stage: BuildDEVDataFactory
  displayName: "Build DEV Data Factory"
  
  variables:
  - group: dev

  jobs:
  - job: ValidateAndBuildDataFactoryTemplate
    displayName: "Build DEV Data Factory"
    steps:
    - template: ci_cd/build.yml
      parameters:
        DEVResourceGroupName: "${{ variables.DEVResourceGroupName }}"
        DEVSubscriptionID: "${{ variables.DEVSubscriptionID }}"
        WorkingDirectory: "${{ variables.WorkingDirectory }}"