name: ADF-CICD-Pipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main 


pool:
  vmImage: "ubuntu-latest"

stages:
- stage: BuildDEVDataFactory
  displayName: "Build DEV Data Factory"
  
  variables:
  - group: dev

  jobs:
  - job: ValidateAndBuildDataFactoryTemplate
    displayName: "Build DEV Data Factory"
    steps:
    - template: ci_cd/build.yml
      parameters:
        DEVResourceGroupName: "$(DEVResourceGroupName)"
        DEVSubscriptionID: "$(DEVSubscriptionID)"
        WorkingDirectory: "$(WorkingDirectory)"




- stage: DeployToUAT
  dependsOn: BuildDEVDataFactory
  condition: succeeded()
  displayName: "Deploy To UAT"

  variables:
  - group: uat

  jobs:
  - deployment: ApprovalCheckDeployToUAT
    displayName: "Approval Check To Deploy To UAT"
    environment: UAT
    strategy:
      runOnce:
        deploy:
          steps:
          - powershell: |
              Write-Host "Deploy To UAT has been fully approved. Starting the deployment to UAT."
  
  
  - job: DeployDataFactory
    displayName: "Deploy ADF ARM Template To Target ADF"
    steps:
    - template: ci_cd/release.yml
      parameters:
        AzureResourceManagerConnection: "$(AzureResourceManagerConnection)"
        DataFactoryName: "$(UATDataFactoryName)"
        #DataFactoryTemplateParametersFilePath: "$(DataFactoryTemplateParametersFilePath)"
        ResourceGroupName: "$(DEVResourceGroupName)"
        SubscriptionID: "$(UATSubscriptionID)"
        WorkingDirectory: "$(WorkingDirectory)"
        ADFArtifactName: "$(ADFArtifactName)"
        Environment: "$(Environment)"

        