parameters:
#- name: DataFactoryName
#  type: string
- name: DEVResourceGroupName
  type: string
- name: DEVSubscriptionID
  type: string
- name: WorkingDirectory # Used to grab the ADF template parameter files and any other files needed to build the ADF
  type: string

  
steps:

- checkout: self
  displayName: "Checkout Source Repo Code"

- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.Repository.LocalPath)'
    verbose: true
  displayName: 'Install npm package'


- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.Repository.LocalPath)' #replace with the package.json folder
    customCommand: "run build validate $(Build.Repository.LocalPath)/resource /subscriptions/'${{ parameters.DEVSubscriptionID }}'/resourceGroups/'${{ parameters.DEVResourceGroupName }}'/providers/Microsoft.DataFactory/factories/nvers"
  displayName: 'Validate'


- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.Repository.LocalPath)' #replace with the package.json folder
    customCommand: "run build export $(Build.Repository.LocalPath)/resource /subscriptions/'${{ parameters.DEVSubscriptionID }}'/resourceGroups/'${{ parameters.DEVResourceGroupName }}'/providers/Microsoft.DataFactory/factories/nvers 'ArmTemplate'"

  displayName: 'Validate and Generate ARM template'

# Publish the artifact to be used as a source for a release pipeline.

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/ArmTemplate' #replace with the package.json folder
    artifact: 'ArmTemplates'
    publishLocation: 'pipeline'